### ISSUE TITLE
OPENAI_API_TYPE error

### ISSUE THREAD

**Issue by MyraBaba** [zekaouinoureddine/Adding-Private-Data-to-LLMs#1]
python rag.py
Traceback (most recent call last):
  File "/home/bc/Projects/OpenSource/Adding-Private-Data-to-LLMs/rag.py", line 27, in <module>
    os.environ['OPENAI_API_TYPE'] = os.getenv('OPENAI_API_TYPE')
  File "/usr/lib/python3.10/os.py", line 685, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.10/os.py", line 757, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

**Comment by zekaouinoureddine** [comment]
To fix the error, make sure you have a `.env` file in the main project directory with the following key-value pairs:

**.env**
```dotenv
OPENAI_API_KEY="<your_actual_api_key>"
OPENAI_API_TYPE="azure"
OPENAI_API_VERSION="2023-03-15-preview"
OPENAI_API_BASE="https://<your_actual_endpoint>.openai.azure.com/"
```

This file specifies the configuration settings, and you need to replace the placeholder values with your actual **OpenAI API key** and endpoint information.

Alternatively, if you prefer not to use a `.env` file, you can set the environment variables directly in your `rag.py` file:

```python
import os

os.environ['OPENAI_API_KEY'] = "<your_actual_api_key>"
os.environ['OPENAI_API_TYPE'] = "azure"
os.environ['OPENAI_API_VERSION'] = "2023-03-15-preview"
os.environ['OPENAI_API_BASE'] = "https://<your_actual_endpoint>.openai.azure.com/"
```

Make sure to replace `your_actual_api_key` and `your_actual_endpoint` with your real OpenAI API key and endpoint values.

**Comment by nayyershahzad** [comment]
is there some other way out? Getting openAI API Key is tricky as they require company email, they don't allow personal emails.

**Comment by zekaouinoureddine** [comment]
Hi @nayyershahzad, I tried it with **Azure OpenAI Studio** credentials. But, if you prefer not to use commercial APIs, you can opt for a completely free RAG pipeline using only **open-source** models from `Hugging Face` for embedding and answer generation. There are many powerful models available.

Check the following blog post:

- [**Ask Your Web Pages Using Mistral-7b & LangChain**](https://medium.com/@zekaouinoureddine/ask-your-web-pages-using-mistral-7b-langchain-f976e1e151ca) - [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://github.com/zekaouinoureddine/Adding-Private-Data-to-LLMs/blob/master/notebooks/Ask_Your_Web_Pages_En.ipynb)
